### PR TITLE
Sass

### PR DESCRIPTION
**Pull request by manojpanta**
Spent more than an hour for this. But All i did was, changing application.css to application.sass, created scss files for navbar, buttons, forms, and typography and included them into application.sass file. I need to learn more about  benefits of having sass instead of css

### CODE REVIEW

**Review by peregrinebalas — APPROVED** [review]

**Comment by teresa-m-knowles** [comment]
Thanks for your work! I know Sass can be super confusing, I tried to get into it a bit too. 

From what I've seen, it's my understanding that .saass is the older version of Sass. The new one has .scss. I did 'application.scss' instead of 'application.css' or 'application.sass' and it also worked. We should decide which one we want to use, .scss or sass, I'm open to either.

I like the idea of breaking up the stylesheets into "navbar", "typography", etc. But, since we don't have any of those at the moment, I'm not sure if it makes sense to have the import lines. I think right now the build will probably fail, since we don't have those files. We could create the file structure and leave it empty for now, or add the import lines as we need them. 

@Mackenzie-Frey What do you think?

**Comment by Mackenzie-Frey** [comment]
> Thanks for your work! I know Sass can be super confusing, I tried to get into it a bit too.
> 
> From what I've seen, it's my understanding that .saass is the older version of Sass. The new one has .scss. I did 'application.scss' instead of 'application.css' or 'application.sass' and it also worked. We should decide which one we want to use, .scss or sass, I'm open to either.
> 
> I like the idea of breaking up the stylesheets into "navbar", "typography", etc. But, since we don't have any of those at the moment, I'm not sure if it makes sense to have the import lines. I think right now the build will probably fail, since we don't have those files. We could create the file structure and leave it empty for now, or add the import lines as we need them.
> 
> @Mackenzie-Frey What do you think?

My vote is to go with the newest version of `.scss` as it's likely more forward compatible and some of us have used it on previous projects. Presuming we are moving down the .scss route _>
app/assets/stylesheets/application.sass needs to be changed to a .scss file

@teresa-m-knowles What do you mean by "build"? I'm seeing the files on apps/assets/stylesheets. Is that what you're referring to?

**Review by Mackenzie-Frey — CHANGES_REQUESTED** [review]
Change application.sass to application.scss and resolve the discussion with Teresa.

**Comment by manojpanta** [comment]
Sure. Having application.scss fine for me, as long as it works. if you are importing files in application.scss that doesn't exist yet, all of your CSS won't work and gives you errors on the console. I think that's what @teresa-m-knowles  is referring to

**Pull request merged**
